_BASE_: ../Base-bagtricks.yml

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]

MODEL:
  BACKBONE:
    WITH_IBN: True
  HEADS:
    POOL_LAYER: GeneralizedMeanPooling

  LOSSES:
    TRI:
      HARD_MINING: True
      MARGIN: 0.3

DATASETS:
  NAMES: ("AICUP",)
  TESTS: ("AICUP",)

SOLVER:
  BIAS_LR_FACTOR: 1.

  IMS_PER_BATCH: 32
  MAX_EPOCH: 100
  STEPS: [40, 70]
  WARMUP_ITERS: 1000

  CHECKPOINT_PERIOD: 1

TEST:
  EVAL_PERIOD: 100 # We didn't provide eval dataset
  IMS_PER_BATCH: 16

OUTPUT_DIR: logs/AICUP_115/bagtricks_R50-ibn
